### ISSUE TITLE
Crash on windows occasionally ( 0.9.50 beta )

### ISSUE THREAD

**Issue by zhaobenx** [typora/typora-issues#1491]
Version: 0.9.50 beta
Platform: windows 10

Typora sometimes crash and show the message: “程序停止响应”.
logs:
```
ERROR 2018/5/13 下午3:26:15  [RenderProcess 1][Error] Error: Cannot call function 'setEnabled' on missing remote object 95
Error: Cannot call function 'setEnabled' on missing remote object 95
    at throwRPCError (E:\Typora\resources\electron.asar\browser\rpc-server.js:143:17)
    at EventEmitter.<anonymous> (E:\Typora\resources\electron.asar\browser\rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (E:\Typora\resources\electron.asar\browser\api\web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at Object.exception (E:\Typora\resources\electron.asar\renderer\api\remote.js:209:30)
    at metaToValue (E:\Typora\resources\electron.asar\renderer\api\remote.js:213:28)
    at Object.remoteMemberFunction (E:\Typora\resources\electron.asar\renderer\api\remote.js:113:16)
    at file:///E:/Typora/resources/app//app/window/frame.js:1:247209
    at Array.map (<anonymous>)
    at d (file:///E:/Typora/resources/app//app/window/frame.js:1:247168)
    at file:///E:/Typora/resources/app//app/window/frame.js:1:248470
INFO 2018/5/13 下午9:50:18  ------------------start------------------
INFO 2018/5/13 下午9:50:18  typora version: 0.9.50
INFO 2018/5/13 下午9:50:18  addRecentDocument
```
But I don't thinks this log is related to the crash, for the time is much earlier than the crash. It crashes actually just before the restart. 

P.S. This is the second crash since the nearest update. I did not do anything, just live typora open, and browsed the web, and it suddenly crashed without any operation.

**Comment by abnerlee** [comment]
@zhaobenx Could you send us (hi@typora.io) the full `typora.log` ?

**Comment by abnerlee** [comment]
Please try update 0.9.51 which fixed some issues

**Comment by zhaobenx** [comment]
Still crashed when updated to 0.9.51。
And there is no log when crash happens.
```
INFO 2018/5/17 下午12:08:25  addRecentDocument
ERROR 2018/5/17 下午1:04:18  [RenderProcess 1][Error] TypeError: Cannot read property 'get' of undefined
    at Object.F.getMenuBlockType (file:///E:/Typora/resources/app//app/window/frame.js:1:744912)
    at n.changeBlock (file:///E:/Typora/resources/app//app/window/frame.js:1:732626)
    at <anonymous>:1:66
    at <anonymous>:1:90
    at EventEmitter.electron.ipcRenderer.on (E:\Typora\resources\electron.asar\renderer\init.js:75:28)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
INFO 2018/5/17 下午3:55:44  ------------------start------------------
INFO 2018/5/17 下午3:55:44  typora version: 0.9.51
INFO 2018/5/17 下午3:55:44  addRecentDocument
```
The crash happens just before I restarted it, but in the log there is no information.
Before crash, I am working on other apps, and just uses alt+tab to read typora, and my cursor is above some math functions, so it is in editing state. Don't know if the crash is related to the math or something?

**Comment by zhaobenx** [comment]
@abnerlee  Please reopen this issue, thx

**Comment by zhaobenx** [comment]
![image](https://user-images.githubusercontent.com/23143530/40267978-20343066-5b98-11e8-9ae9-c7abbe47c30f.png)

![image](https://user-images.githubusercontent.com/23143530/40267945-bfb86892-5b97-11e8-8273-92f4420dace4.png)
It crashes again, and  I press the debug button using VS, but I don't know what is this problem.

**Comment by onceSS** [comment]
I have the same problem.
windows 10 1607, typora 0.9.51, using Chinese in app.
Crashing only happens after I lock down my computer, and appear crash window when I re-login windows.

**Comment by xingdaos** [comment]
me too.
windows 10 1607, typora 0.9.56, using Chinese in app.
Crashing only happens after when the  sleepping computer be wake up.
![image](https://user-images.githubusercontent.com/33388842/44574343-b7d96200-a7bb-11e8-84c7-9f617e3c1b06.png)

**Comment by abnerlee** [comment]
upgrade from Electron 3.x to 5.x 
Close this since it is not updated in long time. Feel free to reopen this if it still happens in latest version
