### ISSUE TITLE
Uncaught Error: Could not call remote function 'setAutoHideMenuBar'.

### ISSUE THREAD

**Issue by Honghe** [typora/typora-issues#1538]
Environment:
* Ubuntu 16.04.4
* Typora 0.9.53

```
Uncaught Error: Could not call remote function 'setAutoHideMenuBar'. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from undefined
Error: Could not call remote function 'setAutoHideMenuBar'. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from undefined
    at callFunction (/home/honsa/a/app/Typora-linux-x64/resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/home/honsa/a/app/Typora-linux-x64/resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/home/honsa/a/app/Typora-linux-x64/resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at callFunction (/home/honsa/a/app/Typora-linux-x64/resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/home/honsa/a/app/Typora-linux-x64/resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/home/honsa/a/app/Typora-linux-x64/resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at Object.exception (/home/honsa/a/app/Typora-linux-x64/resources/electron.asar/renderer/api/remote.js:209:30)
    at metaToValue (/home/honsa/a/app/Typora-linux-x64/resources/electron.asar/renderer/api/remote.js:213:28)
    at Object.remoteMemberFunction (/home/honsa/a/app/Typora-linux-x64/resources/electron.asar/renderer/api/remote.js:113:16)
    at file:///home/honsa/a/app/Typora-linux-x64/resources/app//app/window/frame.js:1:4076
    at CallbacksRegistry.apply (/home/honsa/a/app/Typora-linux-x64/resources/electron.asar/common/api/callbacks-registry.js:47:25)
    at EventEmitter.ipcRenderer.on (/home/honsa/a/app/Typora-linux-x64/resources/electron.asar/renderer/api/remote.js:261:21)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

**Comment by abnerlee** [comment]
should be fixed in new release
