### ISSUE TITLE
Typora 0.9.60 (beta) .log file gets huge - full of error FSEvent.FSWatcher._handle.onchange (fs.js:1385:22)

### ISSUE THREAD

**Issue by vehnamat** [typora/typora-issues#1984]
After a while of inactivity, Typora suddenly uses 100% cpu and starts to write this same error message to typora.log file. In a few minutes the file is hundreds of megabytes and after hour or so - its in gigabytes.

typora-old.log
```
ERROR 27.11.2018 klo 13.04.52  [RenderProcess 1][Error] TypeError: Cannot read property 'close' of undefined
    at FSEvent.FSWatcher._handle.onchange (fs.js:1385:22)
```

^^ that line repeats 378000 times and the last line is:

```
ERROR 27.11.2018 klo 13.06.17  [RenderProcess 1][Error] TypeError: Cannot read property 'close' of undefined
    at FSEvent.FSWatcher._handle.onchange (fs.js:1385:22)
INFO 27.11.2018 klo 13.06.17  ------------------quit------------------
```
Quit happens when i manually close the program.

- Typora is version 0.9.60 (beta)
- The file that iam editing is on a network drive
- Os is Windows 10
- I have uninstalled / reinstalled typora
- No custom themes in use

**Comment by gppk** [comment]
I am also working on Typora version 0.9.60(beta) and just realised my log file is 8.4Gb in size. This seems far too big for a log file, I can't open it to view the contents because it is too large though.

Same as issue above:


    Typora is version 0.9.60 (beta)
    The file that iam editing is on a network drive
    Os is Windows 10
    No custom themes in use
