### ISSUE TITLE
Debian crash

### ISSUE THREAD

**Issue by microcreators** [typora/typora-issues#3774]
Hi. I'm on the latest stable version (I believe) from your repo: 0.9.93-1.
Launching typora after this recent upgrade now results in:
```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: CreateListFromArrayLike called on non-object
    at /usr/share/typora/resources/app/atom.asar/atom.js:511:33
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/usr/share/typora/resources/app/atom.asar/atom.js:506:14)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Object.<anonymous> (electron/js2c/browser_init.js:6122:12)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:6129:30)
    at __webpack_require__ (electron/js2c/browser_init.js:20:30)
    at electron/js2c/browser_init.js:84:18
    at electron/js2c/browser_init.js:87:10
    at NativeModule.compile (internal/bootstrap/loaders.js:287:5)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:222:8)
    at loadNativeModule (internal/modules/cjs/helpers.js:23:9)
    at Module._load (internal/modules/cjs/loader.js:698:15)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1056:10)
    at internal/main/run_main_module.js:17:11
```
Any idea what can be wrong here? For a reason I'm running it as root with `--no-sandbox` param. Was smooth until now.
Thanks.

ps. sysinfo:
`Linux xxx 5.7.0-kali1-amd64 #1 SMP Debian 5.7.6-1kali2 (2020-07-01) x86_64 GNU/Linux`

**Comment by microcreators** [comment]
OK - ignore me. Found it here as well: https://github.com/typora/typora-issues/issues/3733

**Comment by abnerlee** [comment]
Yes, it should be #3733
