### ISSUE TITLE
Popup "ENOENT: No such file or directory" cannot be closed

### ISSUE THREAD

**Issue by lucidBrot** [typora/typora-issues#3775]
![image](https://user-images.githubusercontent.com/4920691/89757473-a5aa7880-dae5-11ea-830b-7c71fdf4cf37.png)

## Reproduction
Open a file that does not yet exist.
```Bash
typora tmp.xxt &>/dev/null &
# or even just
typora tmp.xxt
```
Then typora will open the file, as expected, and when saving, the file will be saved to that path. That's perfect! But also, completely unasked for in my case, above popup appears, saying 
> ENOENT: no such file or directory open '/home/generic/tmp.xxt'

This popup remains there until typora has been fully closed. I had another file open already in typora, so even <kbd>CTRL</kbd><kbd>C</kbd> on my command did not make the popup go away.

## Expected Behaviour
No notification. I wouldn't even need any indication apart from that the file is already unsaved at the time I open it (the dot next to the filename in the tile bar).
At least a popup that could be closed with <kbd>Esc</kbd> or a mouse click instead of a popup that remains until typora is fully closed.

## Version
```bash
$ typora --version
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: CreateListFromArrayLike called on non-object
    at /usr/share/typora/resources/app/atom.asar/atom.js:511:33
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/usr/share/typora/resources/app/atom.asar/atom.js:506:14)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Object.<anonymous> (electron/js2c/browser_init.js:6122:12)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:6129:30)
    at __webpack_require__ (electron/js2c/browser_init.js:20:30)
    at electron/js2c/browser_init.js:84:18
    at electron/js2c/browser_init.js:87:10
    at NativeModule.compile (internal/bootstrap/loaders.js:287:5)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:222:8)
    at loadNativeModule (internal/modules/cjs/helpers.js:23:9)
    at Module._load (internal/modules/cjs/loader.js:698:15)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1056:10)
    at internal/main/run_main_module.js:17:11
```

But the `Help > About` in the GUI shows `version 0.9.93(beta)`.
I'm on linux.
```bash
$ uname -a
Linux motorbrot 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by abnerlee** [comment]
There's no close button on the error dialog?

**Comment by lucidBrot** [comment]
> There's no close button on the error dialog?
No. On windows, there is. On linux there is not.

**Comment by abnerlee** [comment]
What's your Ubuntu and Typora version?

In my test, there is a ok button

**Comment by abnerlee** [comment]
should be fixed in new release

**Comment by fntp** [comment]
并没有修复好吗？到底在搞什么鬼？又他妈有这个问题
