### ISSUE TITLE
Crash on going to sleep

### ISSUE THREAD

**Issue by AlvaroDeMenard** [typora/typora-issues#3922]
```
INFO 10/17/2020, 4:12:50 AM  The system is going to sleep
ERROR 10/17/2020, 4:12:50 AM  TypeError: Cannot read property 'webContents' of null
    at C:\Program Files\Typora\resources\app\atom.asar\DocumentController.js:300:22
    at Set.forEach (<anonymous>)
    at PowerMonitor.<anonymous> (C:\Program Files\Typora\resources\app\atom.asar\DocumentController.js:299:19)
    at PowerMonitor.emit (events.js:223:5)
    at PowerMonitor.EventEmitter.emit (domain.js:475:20)
    at PowerMonitor.topLevelDomainCallback (domain.js:130:23)
```

**Comment by abnerlee** [comment]
which version?

**Comment by AlvaroDeMenard** [comment]
0.9.95, win10

**Comment by LinqLover** [comment]
Same issue, appears to still exist in 0.9.96. I saw the error after resuming my PC from standby.

**Comment by abnerlee** [comment]
would you update to latest version?
