### ISSUE TITLE
export does not work

### ISSUE THREAD

**Issue by Icejl** [typora/typora-issues#4871]
ERROR 2021/12/2 10:44:33  unhandledRejection Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at WebFrame.e.startsWith.e.startsWith.WebFrame.<computed> [as _executeJavaScript] (electron/js2c/renderer_init.js:89:1563)
    at electron/js2c/renderer_init.js:117:435
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:101:375)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:93:1117)

version： 1.0.2 （Already activated）
system：  windows 10

**Comment by abnerlee** [comment]
Export to which format? Is there any error dialog / message from UI ?

**Comment by Icejl** [comment]
Exported to pdf ,it worked.
Because after closing typora, the background process has not ended, just terminate the process and restart the program.
