### ISSUE TITLE
picgo-core 错误无法使用

### ISSUE THREAD

**Issue by Dagwbl** [typora/typora-issues#5309]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
突然picgo就无法上传了，在软件里重新下载也还是一样报错，报错截图如下

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/39078825/175036207-7cb5fe0f-1333-43bf-9ea0-2ef78f39582e.png)

**错误代码**

'''shell
@chcp 65001 >nul & cmd /d/s/c C:\Users\Sky\AppData\Roaming\Typora\picgo\win64\picgo.exe u "C:\\Users\\Sky\\AppData\\Local\\Temp/typora-icon2.png" "C:\\Users\\Sky\\AppData\\Local\\Temp/typora-icon.png"

C:\Users\Sky\AppData\Roaming\Typora\picgo\win64\node_modules\lowdb\adapters\FileSync.js:42
throw e;
^
Error: Line 5: Unexpected token ILLEGAL
at ErrorHandler.constructError (C:\Users\Sky\AppData\Roaming\Typora\picgo\win64\node_modules\esprima\dist\esprima.js:5012:22)
at ErrorHandler.createError (C:\Users\Sky\AppData\Roaming\Typora\picgo\win64\node_modules\esprima\dist\esprima.js:5028:27)
at ErrorHandler.throwError (C:\Users\Sky\AppData\Roaming\Typora\picgo\win64\node_modules\esprima\dist\esprima.js:5035:21)
at Scanner.throwUnexpectedToken (C:\Users\Sky\AppData\Roaming\Typora\picgo\win64\node_modules\esprima\dist\esprima.js:5164:35)
at Scanner.scanStringLiteral (C:\Users\Sky\AppData\Roaming\Typora\picgo\win64\node_modules\esprima\dist\esprima.js:5938:19)
at Scanner.lex (C:\Users\Sky\AppData\Roaming\Typora\picgo\win64\node_modules\esprima\dist\esprima.js:6240:26)
at Tokenizer.getNextToken (C:\Users\Sky\AppData\Roaming\Typora\picgo\win64\node_modules\esprima\dist\esprima.js:6675:84)
at Object.tokenize (C:\Users\Sky\AppData\Roaming\Typora\picgo\win64\node_modules\esprima\dist\esprima.js:154:36)
at tokenize (C:\Users\Sky\AppData\Roaming\Typora\picgo\win64\node_modules\comment-json\src\parse.js:16:34)
at FileSync.parse [as deserialize] (C:\Users\Sky\AppData\Roaming\Typora\picgo\win64\node_modules\comment-json\src\parse.js:341:12) {
index: 87,
lineNumber: 5,
description: 'Unexpected token ILLEGAL'
}
'''

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11 64bit]

**Typora Version**
 1.3.6

**Additional context**

**Comment by Dagwbl** [comment]
经过排查发现是配置文件错误，抱歉
