### ISSUE TITLE
Problem installing Typora on Raspbian 

### ISSUE THREAD

**Issue by deluxtrade** [typora/typora-issues#701]
Is there any solution for this please:

`$ sudo add-apt-repository 'deb https://typora.io ./linux/'
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 167, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 105, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 595, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 89, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/jessie
`

I have followed these instructions:

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BA300B7755AFCFAE
sudo add-apt-repository 'deb https://typora.io ./linux/'
sudo apt-get update
sudo apt-get install typora

**Many thanks for your help.**

**Comment by abnerlee** [comment]
Typora only supports x86 and amd64 architecture. So Raspberry Pi seems not supported
