### ISSUE TITLE
Create new file from the command line

### ISSUE THREAD

**Issue by iafisher** [typora/typora-issues#721]
On Ubuntu 14.04, if you type `$ typora some-nonexisting-filename`, then Typora will display an error. By analogy with other editors, I would expect Typora to silently create the new file, or at least display a useful, non-technical error message.

The exact error message (which comes up in a pop-up window) is:

```
Error: ENOENT: no such file or directory, open '/path/to/file'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Object.getContent (file:///usr/share/typora/resources/app//app/window/frame.js:5:16310)
    at new constructor (file:///usr/share/typora/resources/app//app/window/frame.js:8:14531)
    at Object.b.init (file:///usr/share/typora/resources/app//app/window/frame.js:1:11937)
    at HTMLDocument.<anonymous> (file:///usr/share/typora/resources/app//app/window/frame.js:1:9713)
    at k (file:///usr/share/typora/resources/app//app/window/frame.js:2:15460)
    at Object.fireWith [as resolveWith] (file:///usr/share/typora/resources/app//app/window/frame.js:2:16272)
```

**Comment by abnerlee** [comment]
Currently `typora {filename}` can only be used to open file, creating new file is not supported yet

**Comment by abnerlee** [comment]
merge into #1999
